### ISSUE TITLE
Specifications for exception cases

### ISSUE THREAD

**Issue by Danijj89** [alexey-petrusevich/CS_4500_A1_part2#12]
Would it be possible to provide specs for cases like index out of bound exceptions? Should we just ignore, throw an error and exit or? I believe this should be part of the specs since else everyone would return a different value/exit and would be undefined behavior.

**Comment by alexey-petrusevich** [comment]
Exceptions are not allowed.  Will adddocumentation for index out of bounds.

**Comment by alexey-petrusevich** [comment]
Fixed.
