### ISSUE TITLE
Change set method to only allow for indexes smaller than size

### ISSUE THREAD

**Issue by Danijj89** [alexey-petrusevich/CS_4500_A1_part2#14]
Would it be possible to change the set method to only allow for indexes that are smaller than the length (aka number of elements) of the array? Otherwise we we would have to check for null pointers in every loop and and resize the array every time somebody does set(1000) when there could be only one element in the array. Thanks

**Comment by alexey-petrusevich** [comment]
The internal implementation of set() is totally up to you. I've updated the documentation that specifies if index is out of bounds, an error is thrown.
