### ISSUE TITLE
inserted object's ownership

### ISSUE THREAD

**Issue by Danijj89** [alexey-petrusevich/CS_4500_A1_part2#15]
Please provide specs for who would have ownership for the Object that is inserted/set/replaced into the array. Will they make a copy of the object that is passed in or would it just take ownership of the object? Thanks

**Comment by rohitppathak** [comment]
Our implementation made it so the user has responsibility for Objects and Strings that were inserted/set/replaced, so the user would need to delete. For primitives there is no ownership.

**Comment by Danijj89** [comment]
Does this mean that the array will get ownership of the elements passed in? If this is the case then the array will have the responsibility to delete them, is this correct?

**Comment by rohitppathak** [comment]
I believe the user will have the responsibility of deleting them, not the array, since the user is the one that made the Strings and Objects in the first place

**Comment by alexey-petrusevich** [comment]
The internal representation of memory management is totally up to you. You can clear the memory when you delete the array or the user who inserted the values into the array, may clear the values he inserted. It is your call.
