### ISSUE TITLE
Replace int**, float** and bool** with int*, float*, bool*

### ISSUE THREAD

**Issue by yth** [alexey-petrusevich/CS_4500_A1_part2#3]
Actual int, float, and bool can be manipulated just as easily as pointers to int, float, and bool. By tightly packing the actual values, we improve cache efficiency.

**Comment by alexey-petrusevich** [comment]
Will do ASAP. In your design of functionality, you may assume the types have already changed.

**Comment by alexey-petrusevich** [comment]
Issue resolved. Corresponding methods have been fixed as well, including those in StrArray. To the best of my knowledge, tests should not be affected.
