### ISSUE TITLE
Changing primitive pointers to just primitives

### ISSUE THREAD

**Issue by rohitppathak** [alexey-petrusevich/CS_4500_A1_part2#5]
For all the primitive array types, we believe that they should take in only the primitive types, not the actual pointers to the primitives. For instance in the IntArray, the methods which take in an `int*` should take in an `int` instead. This way, we can just do `myIntArr.add(0, 3)` instead of creating a pointer for the integer 3.

**Comment by rohitppathak** [comment]
Sorry, we had a previous version of your code and didn't see that you fixed it. Would you mind updating the test file as well to reflect the changes?

**Comment by alexey-petrusevich** [comment]
Will do ASAP.

**Comment by raacharya** [comment]
thank you!

**Comment by rohitppathak** [comment]
Also for the StrArray, I think it should return a `String*` for methods like `get` rather than just a `String` since it isn't a primitive

**Comment by alexey-petrusevich** [comment]
I changed all pointer types to object types. The return type of String signifies that pointer to a String is being returned. This will have to comply with other methods as well as the tests provided in test-array.cpp. This pretty much means that the internal representation of StrArray should have a String** as its base. The initial implementation was using pointers of pointers, but was later replaced per another team's request. See if you can make it work with String return value.

**Comment by rohitppathak** [comment]
So we looked at the other issue and they requested `Replace int**, float** and bool** with int*, float*, bool*`, which makes sense because these are primitive types. But we think for the StrArray it should still return String* since it is a custom object

**Comment by alexey-petrusevich** [comment]
Does that mean you need the same functionality for a regular Array that should return Object* instead of Object?

**Comment by rohitppathak** [comment]
Yes, sorry we were using an older version of the code so we didn't catch that.

**Comment by alexey-petrusevich** [comment]
In this case, the return type of split() will be Object** and String**.

**Comment by rohitppathak** [comment]
Could you actually change it to Array and StrArray?

**Comment by alexey-petrusevich** [comment]
Array or Array*?

**Comment by rohitppathak** [comment]
Array*

**Comment by alexey-petrusevich** [comment]
Issue resolved. Please let me know if you find any typos. Thanks.
