### ISSUE TITLE
Changing the size function to return number of elements added

### ISSUE THREAD

**Issue by rohitppathak** [alexey-petrusevich/CS_4500_A1_part2#8]
Since we have to make the array bigger when elements are added to it, we believe the size function should return just the number of elements added to the array, not the initial size of the array. This should only affect the test file.

**Comment by alexey-petrusevich** [comment]
Not sure I follow. In any collection implementation, size() always returns the number of elements currently contained in the given collection.

**Comment by rohitppathak** [comment]
So in the test file:
`Array* array2 = new Array(5000);
t_true(array2->len() == 5000);`
even though the length of the elements is 0. Because the spec says `Arrays should grow when values are pushed back`, we double the length of the array when it's full. In that case, we are unsure what the len method should return

**Comment by alexey-petrusevich** [comment]
I see. I'll change the test.

**Comment by rohitppathak** [comment]
Thank you!

**Comment by alexey-petrusevich** [comment]
Corresponding tests have been changed. Let me know if you find any typos. Thanks.
