### ISSUE TITLE
Implementation Questions

### ISSUE THREAD

**Issue by rohitppathak** [alexey-petrusevich/CS_4500_A1_part2#9]
We have some questions about behavior of certain methods of the Array:

1. When should we resize the array? Suppose we make an array of size 5. Should calling the `set` method at index 10 throw an error or extend the array and put the element at index 10? Should calling the `insert` function do the same thing?

2. What is the difference between the two constructors? If the answer to question 1 is to resize the array when `set` and `insert` take in indices which are greater than the capacity, then is there a difference between `new Array()` and `new Array(10)`? Should the first one resize and the second one not?

3. Should calling `remove` on an index which doesn't contain an element throw an error or do nothing?

If you would also be down to meet up quickly at WVH tomorrow to answer some questions, we could also do that. Whatever's easier.

**Comment by alexey-petrusevich** [comment]
1. I don't have tests for array resizing. If you have the ability to resize the array during insertion, then you can implement it.
set() works such that if the element at the given index is present, it is replaced with the given value. If the value is not there, then the given value is placed at the index anyways. The difference is that if there is a new value, you might need to free the memory.
For insert() documentation explains it all - the method inserts a value at the given index, and shift the remaining values to the right.
I think it is up to you how to handle this - resize the array, have a fixed size and discard any values outside of the range, or throw an error.

2. The default constructor is provided so you can create an array with default capacity, for example, 1000 elements. The second constructor gives you the ability to have an array of arbitrary size.

3. It is your implementation. For Object types, you can return nullptr, for value types you can throw an error. Alternatively, you can have any behavior you desire.

**Comment by rohitppathak** [comment]
Got it, thanks!
